spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sap_erp_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


# PHASE 7 - JWT CONFIGURATION

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# PHASE 9 - SAP S/4HANA INTEGRATION
sap.s4hana.base-url=${SAP_S4HANA_BASE_URL}
sap.s4hana.api-key=${SAP_S4HANA_API_KEY}


# SAP S/4HANA Integration
sap.s4hana.enabled=false

# PHASE 10 - SAP AI SDK DEBUG LOGGING
logging.level.com.sap.ai.sdk.orchestration=DEBUG